### ISSUE TITLE
Pass arguments as kwargs instead of dict

### ISSUE THREAD

**Issue by rheinheimer** [hydraplatform/hydra-client-python#6]
I suggest revising the library to accept arguments as kwargs, instead of a dictionary of arguments. For example, instead of `conn.add_network({'net': network})`, one would call `conn.add_network(net=network)`.

Here's my catchall code for a generic call to the hydra-server:
```
    def call(self, fn, **kwargs):
        # convert any boolean parameters to 'Y' or 'N'.
        for kwarg in kwargs.keys():
            if type(kwargs[kwarg]) == bool:
                kwargs[kwarg] = 'Y' if kwargs[kwarg] is True else 'N'
        return self._call(fn, kwargs)
```
I use this as `conn.call('add_network', net=network)`. This could be modified to accommodate specific functions of course:
```
def add_network(self, **kwargs):
    return self.call('add_network', **kwargs)
```

**Comment by jetuk** [comment]
Doesn't it already work like this?

Check the `__getattr__` method of `BaseConnection`. There's no need to implement `add_network` specifically. You can call any HB function via `connection.hb_api_function(*args, **kwarg)` already.

**Comment by rheinheimer** [comment]
@jetuk Thanks!
